# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Python CDK Deployments

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: install web app dependencies
      working-directory: ./web
      run: npm ci

    - name: build web app
      working-directory: ./web
      run: npm run build

    - name: install AWS CDK
      run: sudo npm i -g aws-cdk

    - name: install deployment dependencies
      working-directory: ./py-webdepl
      run: pip3 install -r requirements.txt

    - name: run cdk synth
      working-directory: ./py-webdepl
      run: cdk synth

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role
        aws-region: ${{ secrets.AWS_REGION }}

    - name: verify user credentials
      run: aws sts get-caller-identity

    - name: cdk deploy
      working-directory: ./py-webdepl
      run: cdk deploy
    